version: '3.8'

services:
  code-researcher:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - CONFIG_PATH=/app/config/config.yaml
      - PYTHONPATH=/app
    volumes:
      - ./config/config.yaml:/app/config/config.yaml:ro
      - ./logs:/app/logs
      - /tmp:/tmp  # For temporary workspaces
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
  # Optional: Redis for job queue (future enhancement)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
